# Generated by Django 3.2.6 on 2021-08-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contest',
        ),
    ]
